### ISSUE TITLE
Characterization of raw data

### ISSUE THREAD

**Issue by benjaminboitrelle** [percival-desy/percival-characterization#5]
Modify 2D histogram to get a plot of Coarse Vs Fine for all rows and all frames (fixed ADC and columns)

**Comment by manuelakuhn** [comment]
2D histograms require the arrays for x and y to be one dimensional. If you slice the data through rows and frames you retrieve a 2D-array which have to be flattened before you can use it in the histogram.

e.g.
instead of 
plt.hist2d(data_coarse, data_fine)
use 
plt.hist2d(data_coarse.flatten(), data_fine.flatten())
